tasks:
  - init: |
      echo 'TODO: build project'
    command: |
      docker run -p 9000:9000 -d vistadataproject/nodevista999 && python3 -m pip install visidata && /home/gitpod/.pyenv/versions/3.8.12/bin/visidata "http://localhost:9000/fmqlEP?fmql=DESCRIBE%2050_67%20LIMIT%201000"

